STM32F4USBDEVCLASSHIDCSRC 		:=  $(wildcard $(LOCPATH)/src/*.c)
STM32F4USBDEVCLASSHIDCCSRC 	:=  $(wildcard $(LOCPATH)/src/*.cc)
STM32F4USBDEVCLASSHIDASMSRC	:=  $(wildcard $(LOCPATH)/src/*.S)

#+ CSRC 			+= $(STM32F4USBDEVCLASSHIDCSRC)
#+ CCSRC 		+= $(STM32F4USBDEVCLASSHIDCCSRC)
#+ ASMSRC 		+= $(STM32F4USBDEVCLASSHIDASMSRC)
LIBSRC_CLEAN += $(STM32F4USBDEVCLASSHIDCSRC:%.c=%.o) $(STM32F4USBDEVCLASSHIDCCSRC:%.cc=%.o) $(STM32F4USBDEVCLASSHIDASMSRC:%.S=%.o)

$(LIBUSBCLASSHID): $(STM32F4USBDEVCLASSHIDCSRC:%.c=%.o) $(STM32F4USBDEVCLASSHIDCCSRC:%.cc=%.o) $(STM32F4USBDEVCLASSHIDASMSRC:%.S=%.o)
	$(AR) -cru $@ $^
	$(RANLIB) $@
