STM32F4USBOTGCSRC 	:=  $(wildcard $(LOCPATH)/src/*.c)
STM32F4USBOTGCCSRC 	:=  $(wildcard $(LOCPATH)/src/*.cc)
STM32F4USBOTGASMSRC 	:=  $(wildcard $(LOCPATH)/src/*.S)

#+ CSRC 			+= $(STM32F4USBOTGCSRC)
#+ CCSRC 		+= $(STM32F4USBOTGCCSRC)
#+ ASMSRC 		+= $(STM32F4USBOTGASMSRC)
LIBSRC_CLEAN +=  $(STM32F4USBOTGCSRC:%.c=%.o) $(STM32F4USBOTGCCSRC:%.cc=%.o) $(STM32F4USBOTGASMSRC:%.S=%.o)

$(LIBUSBOTGCORE): $(STM32F4USBOTGCSRC:%.c=%.o) $(STM32F4USBOTGCCSRC:%.cc=%.o) $(STM32F4USBOTGASMSRC:%.S=%.o)
	$(AR) -cru $@ $^
	$(RANLIB) $@
