STM32F4DISCOVERYCSRC 	:=  $(wildcard $(LOCPATH)/src/*.c)
STM32F4DISCOVERYCCSRC	:=  $(wildcard $(LOCPATH)/src/*.cc)
STM32F4DISCOVERYASMSRC 	:=  $(wildcard $(LOCPATH)/src/*.S)

#+ CSRC 			+= $(STM32F4DISCOVERYCSRC)
#+ CCSRC 		+=  $(STM32F4DISCOVERYCCSRC)
#+ ASMSRC 		+=  $(STM32F4DISCOVERYASMSRC)
LIBSRC_CLEAN += $(STM32F4DISCOVERYCSRC:%.c=%.o) $(STM32F4DISCOVERYCCSRC:%.cc=%.o) $(STM32F4DISCOVERYASMSRC:%.S=%.o)

$(LIBSTM32F4DISCOVERY): $(STM32F4DISCOVERYCSRC:%.c=%.o) $(STM32F4DISCOVERYCCSRC:%.cc=%.o) $(STM32F4DISCOVERYASMSRC:%.S=%.o)
	$(AR) -cru $@ $^
	$(RANLIB) $@
