STM32F4CMSISCSRC 		:=  $(wildcard $(LOCPATH)/src/*.c)
STM32F4CMSISCCSRC 	:=  $(wildcard $(LOCPATH)/src/*.cc)
STM32F4CMSISASMSRC 	:=  $(wildcard $(LOCPATH)/src/*.S)

#+ CSRC 			+= $(STM32F4CMSISCSRC)
#+ CCSRC 		+= $(STM32F4CMSISCCSRC)
ASMSRC 		+= $(STM32F4CMSISASMSRC)
LIBSRC_CLEAN += $(STM32F4CMSISCSRC:%.c=%.o) $(STM32F4CMSISCCSRC:%.cc=%.o) 

$(LIBCMSISSTM32F4): $(STM32F4CMSISCSRC:%.c=%.o) $(STM32F4CMSISCCSRC:%.cc=%.o) 
	$(AR) -cru $@ $^
	$(RANLIB) $@
